---
title: "Spatial statistics modeling"
author: "Joel Eliason"
date: "11/23/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lme4)
library(nlme)
library(mgcv)
library(gamm4)
```


```{r}
# df = read_csv("data/CRC_master.csv")
df = read_csv("data/spots_nbhds_df.csv")
# df = df %>%
#   mutate(across(c(groups,spots,patients,ClusterName),factor)) %>%
#   select(-`...1`) %>%
#   rename_all(~str_replace_all(., " - ", "_")) %>%
#   rename_all(~str_replace_all(., " ", "_"))

df = df %>%
  mutate(across(c(patient_group,patient_id,spot_id),factor)) %>%
  rename_all(~str_replace_all(., " ", "_")) %>%
  rename_all(~str_replace_all(., "\\+", "p")) %>%
  rename_all(~str_replace_all(., "\\/",  ""))

df = df[-c(1564,2171),] # these are outliers for binomial glm
cols = colnames(df)
data_cols = cols[6:length(cols)]
# df = df %>%
  # mutate(across(all_of(data_cols),scale))

df

f = paste(cols[6:length(cols)], collapse=' + ') # only using a subset
f = paste0('patient_group ~ ',f)
# f.re = paste0(f,' + (1 | patient_id ) + (1 | patient_id : spot_id)')
f.re = paste0(f,' + (1 + tumor_cells + vasculature + stroma | patient_id )')
f.re = 'patient_group ~ (1 | spot_id ) + (1 | spot_id : patient_id)'

m <- glmer(f.re, data=df,family = binomial)
m.glm = glm(f,data = df, family = binomial)

summary(m)

summary(m.glm)

pred = predict(m.glm, df, type="response")

# m <- lme(CD44_stroma ~ ClusterName,random = ~1|spots, correlation = corExp(form = ~X + Y|spots), data = df)
# 
# m2 <- gls(CD44_stroma ~ ClusterName, data = df, verbose = T)
# vario2 <- Variogram(m2, form = ~X + Y, resType = "pearson")

library(corrplot)
cor_sel = function(X,threshold=0.2,breadth=1) {
  correlation_matrix = cor(X)
  threshold <- 0.2
  breadth <- 1
  correlation_matrix_filter <- correlation_matrix
  diag(correlation_matrix_filter) <- 0
  filter <- apply(correlation_matrix_filter,1, function(x) sum(abs(x) >= threshold,na.rm = T))
  sel <- filter >= breadth
  correlation_matrix_final <- correlation_matrix[sel,sel]
  correlation_matrix_final
}
```

```{r}
corrplot(cor_sel(df %>% filter(patient_group == 1) %>% select(-c(patient_group,patient_id,spot_id,centroid_X,centroid_Y))),diag = F)

corrplot(cor_sel(df %>% filter(patient_group == 2) %>% select(-c(patient_group,patient_id,spot_id,centroid_X,centroid_Y))),diag = F)

corrplot(cor_sel(df %>% filter(patient_id == 1) %>% select(-c(patient_group,patient_id,spot_id,centroid_X,centroid_Y))),diag = F,type = 'lower', order = "AOE")

```

```{r}
set.seed(12358)
N = 3e6                                  # total sample size
n_groups = 1000                          # number of groups
g = rep(1:n_groups, e = N/n_groups)      # the group identifier

x = rnorm(N)                             # an observation level continuous variable
b = rbinom(n_groups, size = 1, prob=.5)  # a cluster level categorical variable
b = b[g]

sd_g = .5     # standard deviation for the random effect
sigma = 1     # standard deviation for the observation

re0 = rnorm(n_groups, sd = sd_g)  # random effects
re  = re0[g]

lp = 0 + .5*x + .25*b + re        # linear predictor 

y = rnorm(N, mean = lp, sd = sigma)               # create a continuous target variable
y_bin = rbinom(N, size = 1, prob = plogis(lp))    # create a binary target variable

d = tibble(x, b, y, y_bin, g = factor(g))
```


```{r}
library(lme4)

system.time({
  mixed_big = lmer(y ~ x + b + (1|g))
})

system.time({
  mixed_big = lme(y ~ x + b, random = ~1|g)
})
```

```{r}
system.time({
  # m <- gamm4(CD44_stroma ~ ClusterName,random = ~1|spots, correlation = corExp(form = ~X + Y|spots), data = df)
  m = gam(
  CD44_stroma ~ ClusterName + s(spots, bs = 're'),
  data = df,
  method = 'REML'
)
})

```

